name: Deploy React Frontend with Docker

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
            echo "DOCKER_TAG=latest" >> $GITHUB_ENV
            echo "EBS_ENV=${{ secrets.EBS_ENV_PRODUCTION }}" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
            echo "DOCKER_TAG=staging" >> $GITHUB_ENV
            echo "EBS_ENV=${{ secrets.EBS_ENV_STAGING }}" >> $GITHUB_ENV
          fi

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/shopping-frontend:$DOCKER_TAG .
          docker push ${{ secrets.DOCKER_USERNAME }}/shopping-frontend:$DOCKER_TAG

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Node.js and AWS SDK v3
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install AWS SDK v3
        run: npm install @aws-sdk/client-elastic-beanstalk @aws-sdk/client-s3 dotenv

      - name: Fetch Elastic Beanstalk S3 Bucket (Using AWS SDK v3)
        run: node .github/scripts/get-s3-bucket.js

      - name: Update Dockerrun.aws.json with correct image tag
        run: |
          sed -i 's|"Name": ".*"|\"Name\": \"${{ secrets.DOCKER_USERNAME }}/shopping-frontend:$DOCKER_TAG\"|' Dockerrun.aws.json

      - name: Generate new deployment version
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          echo "VERSION_LABEL=shopping-frontend-${ENVIRONMENT}-${TIMESTAMP}" >> $GITHUB_ENV

      - name: Upload Dockerrun.aws.json to S3 (Using AWS SDK v3)
        run: node .github/scripts/upload-to-s3.js
             sleep 10  # Give time for the file to appear in S3
        

      - name: Create new Elastic Beanstalk application version (Using AWS SDK v3)
        run: node .github/scripts/create-eb-version.js
             sleep 10  # Wait for AWS to process the version

      - name: Deploy to Elastic Beanstalk (Using AWS SDK v3)
        run: node .github/scripts/deploy-eb.js
