name: Deploy React Frontend with Docker

on:
  push:
    branches:
      - main  # Deploys to Production
      - staging  # Deploys to Staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
            echo "DOCKER_TAG=latest" >> $GITHUB_ENV
            echo "EBS_ENV=${{ secrets.EBS_ENV_PRODUCTION }}" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
            echo "DOCKER_TAG=staging" >> $GITHUB_ENV
            echo "EBS_ENV=${{ secrets.EBS_ENV_STAGING }}" >> $GITHUB_ENV
          fi

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/shopping-frontend:$DOCKER_TAG .
          docker push ${{ secrets.DOCKER_USERNAME }}/shopping-frontend:$DOCKER_TAG

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Fetch Elastic Beanstalk S3 Bucket
        run: |
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
          S3_BUCKET="elasticbeanstalk-${{ secrets.AWS_REGION }}-${AWS_ACCOUNT_ID}"
          echo "S3_BUCKET=$S3_BUCKET" >> $GITHUB_ENV

      - name: Update Dockerrun.aws.json with correct image tag
        run: |
          sed -i 's|"Name": ".*"|\"Name\": \"${{ secrets.DOCKER_USERNAME }}/shopping-frontend:$DOCKER_TAG\"|' Dockerrun.aws.json

      - name: Generate new deployment version
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          echo "VERSION_LABEL=shopping-frontend-${ENVIRONMENT}-${TIMESTAMP}" >> $GITHUB_ENV

      - name: Upload Dockerrun.aws.json to S3
        run: |
          aws s3 cp Dockerrun.aws.json s3://$S3_BUCKET/shopping-frontend-${VERSION_LABEL}.json

      - name: Create new Elastic Beanstalk application version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name shopping-react-app \
            --version-label $VERSION_LABEL \
            --source-bundle S3Bucket=$S3_BUCKET,S3Key=shopping-frontend-${VERSION_LABEL}.json

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --application-name shopping-react-app \
            --environment-name $EBS_ENV \
            --version-label $VERSION_LABEL
