name: Deploy React Frontend with Docker

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
            echo "DOCKER_TAG=latest" >> $GITHUB_ENV
            echo "EBS_ENV=${{ secrets.EBS_ENV_PRODUCTION }}" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
            echo "DOCKER_TAG=staging" >> $GITHUB_ENV
            echo "EBS_ENV=${{ secrets.EBS_ENV_STAGING }}" >> $GITHUB_ENV
          fi

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/shopping-frontend:$DOCKER_TAG .
          docker push ${{ secrets.DOCKER_USERNAME }}/shopping-frontend:$DOCKER_TAG

      - name: Set up Node.js and install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install AWS SDK v3 dependencies
        run: npm install @aws-sdk/client-elastic-beanstalk @aws-sdk/client-s3 @aws-sdk/client-sts dotenv

      - name: Fetch Elastic Beanstalk S3 Bucket
        run: node .github/scripts/get-s3-bucket.js

      - name: Update Dockerrun.aws.json with correct image tag
        run: |
          sed -i 's|"Name": ".*"|\"Name\": \"${{ secrets.DOCKER_USERNAME }}/shopping-frontend:$DOCKER_TAG\"|' Dockerrun.aws.json

      - name: Generate new deployment version
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          echo "VERSION_LABEL=shopping-frontend-${ENVIRONMENT}-${TIMESTAMP}" >> $GITHUB_ENV

      - name: Upload Dockerrun.aws.json to S3
        run: node .github/scripts/upload-to-s3.js

      - name: Create new Elastic Beanstalk application version
        run: node .github/scripts/create-eb-version.js

      - name: Deploy to Elastic Beanstalk
        run: node .github/scripts/deploy-eb.js
